#!/usr/bin/python
#coding=utf-8

#Gracias a raise podemos lanzar un error manual pas치ndole el identificador. 
#Luego simplemente podemos a침adir un except para tratar esta excepci칩n 
#que hemos lanzado
def mi_funcion(algo=None):
    try:
        if algo is None:
            raise ValueError("Error! No se permite un valor nulo")
    except ValueError:
        print("Error! No se permite un valor nulo (desde la excepci칩n)")
mi_funcion()